# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
includes_dir: _includes
collections:
  posts:
    output:   true

# Handling Reading
safe:                 true
exclude:              [
  "*/README.md",
  "Gemfile",
  "Gemfile.lock",
  "Makefile",
  "node_modules",
  "README.md",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/"
]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
url:     "https://peakrisksolutions.com"
# baseurl: "/peakrisksolutions"
show_dir_listing: false

# Outputting
permalink:     /:title/
timezone:      null

quiet:    false
verbose:  false
defaults:
  -
    values:
      layout: "default"
      contact_notice: true